trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' # Ajuste para a versão do Node.js que você está usando
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm run build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
