trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x' 
  displayName: 'Install Node.js'

- script: |
    node -v
    npm -v
    npm install --legacy-peer-deps
    npm run build
  displayName: 'Install dependencies and build'
  
- script: |
    echo "Build folder contents:"
    ls -al build
  displayName: 'List build directory contents'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
