export * from './home'
export * from './about'
export * from './projects'
export * from './contact'
export * from './repositories'
export * from './private'
export * from './certificate'
export * from './feedback'
